package hr.fer.oop;

import java.util.ArrayList;
import java.util.List;

public class LoadData {
	public static List<GameInfo> loadGInfData() {
		List<GameInfo> ginflist = new ArrayList<>();
		
		ginflist.add(new GameInfo(1, "Manchester Utd", "Fulham", 1, 0, "Old Trafford", 73297));
		ginflist.add(new GameInfo(1, "Ipswich Town", "Liverpool", 0, 2, "Portman Road Stadium", 30014));
		ginflist.add(new GameInfo(1, "Newcastle Utd", "Southampton", 1, 0, "St James' Park", 52196));
		ginflist.add(new GameInfo(1, "Everton", "Brighton", 0, 3, "Goodison Park", 39217));
		ginflist.add(new GameInfo(1, "Nott'ham Forest", "Bournemouth", 1, 1, "The City Ground", 29763));
		ginflist.add(new GameInfo(1, "Arsenal", "Wolves", 2, 0, "Emirates Stadium", 60261));
		ginflist.add(new GameInfo(1, "West Ham", "Aston Villa", 1, 2, "London Stadium", 62463));
		ginflist.add(new GameInfo(1, "Brentford", "Crystal Palace", 2, 1, "Gtech Community Stadium", 16988));
		ginflist.add(new GameInfo(1, "Chelsea", "Manchester City", 0, 2, "Stamford Bridge", 39818));
		ginflist.add(new GameInfo(1, "Leicester City", "Tottenham", 1, 1, "King Power Stadium", 31977));
		ginflist.add(new GameInfo(2, "Brighton", "Manchester Utd", 2, 1, "The American Express Stadium", 31537));
		ginflist.add(new GameInfo(2, "Manchester City", "Ipswich Town", 4, 1, "Etihad Stadium", 53147));
		ginflist.add(new GameInfo(2, "Southampton", "Nott'ham Forest", 0, 1, "St Mary's Stadium", 31150));
		ginflist.add(new GameInfo(2, "Tottenham", "Everton", 4, 0, "Tottenham Hotspur Stadium", 61357));
		ginflist.add(new GameInfo(2, "Fulham", "Leicester City", 2, 1, "Craven Cottage", 25401));
		ginflist.add(new GameInfo(2, "Crystal Palace", "West Ham", 0, 2, "Selhurst Park", 25099));
		ginflist.add(new GameInfo(2, "Aston Villa", "Arsenal", 0, 2, "Villa Park", 41587));
		ginflist.add(new GameInfo(2, "Wolves", "Chelsea", 2, 6, "Molineux Stadium", 31235));
		ginflist.add(new GameInfo(2, "Bournemouth", "Newcastle Utd", 1, 1, "Vitality Stadium", 11161));
		ginflist.add(new GameInfo(2, "Liverpool", "Brentford", 2, 0, "Anfield", 60017));
		ginflist.add(new GameInfo(3, "Arsenal", "Brighton", 1, 1, "Emirates Stadium", 60326));
		ginflist.add(new GameInfo(3, "Ipswich Town", "Fulham", 1, 1, "Portman Road Stadium", 29517));
		ginflist.add(new GameInfo(3, "Nott'ham Forest", "Wolves", 1, 1, "The City Ground", 29918));
		ginflist.add(new GameInfo(3, "Brentford", "Southampton", 3, 1, "Gtech Community Stadium", 16955));
		ginflist.add(new GameInfo(3, "Leicester City", "Aston Villa", 1, 2, "King Power Stadium", 31725));
		ginflist.add(new GameInfo(3, "Everton", "Bournemouth", 2, 3, "Goodison Park", 38805));
		ginflist.add(new GameInfo(3, "West Ham", "Manchester City", 1, 3, "London Stadium", 62469));
		ginflist.add(new GameInfo(3, "Newcastle Utd", "Tottenham", 2, 1, "St James' Park", 52211));
		ginflist.add(new GameInfo(3, "Chelsea", "Crystal Palace", 1, 1, "Stamford Bridge", 39298));
		ginflist.add(new GameInfo(3, "Manchester Utd", "Liverpool", 0, 3, "Old Trafford", 73738));
		ginflist.add(new GameInfo(4, "Southampton", "Manchester Utd", 0, 3, "St Mary's Stadium", 31144));
		ginflist.add(new GameInfo(4, "Manchester City", "Brentford", 2, 1, "Etihad Stadium", 52148));
		ginflist.add(new GameInfo(4, "Liverpool", "Nott'ham Forest", 0, 1, "Anfield", 60344));
		ginflist.add(new GameInfo(4, "Crystal Palace", "Leicester City", 2, 2, "Selhurst Park", 25147));
		ginflist.add(new GameInfo(4, "Fulham", "West Ham", 1, 1, "Craven Cottage", 26528));
		ginflist.add(new GameInfo(4, "Brighton", "Ipswich Town", 0, 0, "The American Express Stadium", 41573));
		ginflist.add(new GameInfo(4, "Aston Villa", "Everton", 3, 2, "Villa Park", 41573));
		ginflist.add(new GameInfo(4, "Bournemouth", "Chelsea", 0, 1, "Vitality Stadium", 11235));
		ginflist.add(new GameInfo(4, "Tottenham", "Arsenal", 0, 1, "Tottenham Hotspur Stadium", 61645));
		ginflist.add(new GameInfo(4, "Wolves", "Newcastle Utd", 1, 2, "Molineux Stadium", 30255));
		ginflist.add(new GameInfo(5, "West Ham", "Chelsea", 0, 3, "London Stadium", 62473));
		ginflist.add(new GameInfo(5, "Tottenham", "Brentford", 3, 1, "Tottenham Hotspur Stadium", 61246));
		ginflist.add(new GameInfo(5, "Aston Villa", "Wolves", 3, 1, "Villa Park", 39978));
		ginflist.add(new GameInfo(5, "Fulham", "Newcastle Utd", 3, 1, "Craven Cottage", 25700));
		ginflist.add(new GameInfo(5, "Southampton", "Ipswich Town", 1, 1, "St Mary's Stadium", 31117));
		ginflist.add(new GameInfo(5, "Leicester City", "Everton", 1, 1, "King Power Stadium", 31765));
		ginflist.add(new GameInfo(5, "Liverpool", "Bournemouth", 3, 0, "Anfield", 60347));
		ginflist.add(new GameInfo(5, "Crystal Palace", "Manchester Utd", 0, 0, "Selhurst Park", 25172));
		ginflist.add(new GameInfo(5, "Brighton", "Nott'ham Forest", 2, 2, "The American Express Stadium", 31444));
		ginflist.add(new GameInfo(5, "Manchester City", "Arsenal", 2, 2, "Etihad Stadium", 52846));
		ginflist.add(new GameInfo(6, "Newcastle Utd", "Manchester City", 1, 1, "St James' Park", 52248));
		ginflist.add(new GameInfo(6, "Brentford", "West Ham", 1, 1, "Gtech Community Stadium", 17050));
		ginflist.add(new GameInfo(6, "Everton", "Crystal Palace", 2, 1, "Goodison Park", 38954));
		ginflist.add(new GameInfo(6, "Arsenal", "Leicester City", 4, 2, "Emirates Stadium", 60323));
		ginflist.add(new GameInfo(6, "Chelsea", "Brighton", 4, 2, "Stamford Bridge", 39495));
		ginflist.add(new GameInfo(6, "Nott'ham Forest", "Fulham", 0, 1, "The City Ground", 30139));
		ginflist.add(new GameInfo(6, "Wolves", "Liverpool", 1, 2, "Molineux Stadium", 31413));
		ginflist.add(new GameInfo(6, "Ipswich Town", "Aston Villa", 2, 2, "Portman Road Stadium", 29943));
		ginflist.add(new GameInfo(6, "Manchester Utd", "Tottenham", 0, 3, "Old Trafford", 73587));
		ginflist.add(new GameInfo(6, "Bournemouth", "Southampton", 3, 1, "Vitality Stadium", 11243));
		ginflist.add(new GameInfo(7, "Crystal Palace", "Liverpool", 0, 1, "Selhurst Park", 25185));
		ginflist.add(new GameInfo(7, "Brentford", "Wolves", 5, 3, "Gtech Community Stadium", 16960));
		ginflist.add(new GameInfo(7, "Leicester City", "Bournemouth", 1, 0, "King Power Stadium", 31706));
		ginflist.add(new GameInfo(7, "Manchester City", "Fulham", 3, 2, "Etihad Stadium", 53017));
		ginflist.add(new GameInfo(7, "West Ham", "Ipswich Town", 4, 1, "London Stadium", 62467));
		ginflist.add(new GameInfo(7, "Arsenal", "Southampton", 3, 1, "Emirates Stadium", 60307));
		ginflist.add(new GameInfo(7, "Everton", "Newcastle Utd", 0, 0, "Goodison Park", 39265));
		ginflist.add(new GameInfo(7, "Aston Villa", "Manchester Utd", 0, 0, "Villa Park", 42682));
		ginflist.add(new GameInfo(7, "Chelsea", "Nott'ham Forest", 1, 1, "Stamford Bridge", 39501));
		ginflist.add(new GameInfo(7, "Brighton", "Tottenham", 3, 2, "The American Express Stadium", 31487));
		ginflist.add(new GameInfo(8, "Tottenham", "West Ham", 4, 1, "Tottenham Hotspur Stadium", 61381));
		ginflist.add(new GameInfo(8, "Fulham", "Aston Villa", 1, 3, "Craven Cottage", 26743));
		ginflist.add(new GameInfo(8, "Ipswich Town", "Everton", 0, 2, "Portman Road Stadium", 29862));
		ginflist.add(new GameInfo(8, "Southampton", "Leicester City", 2, 3, "St Mary's Stadium", 31145));
		ginflist.add(new GameInfo(8, "Manchester Utd", "Brentford", 2, 1, "Old Trafford", 73738));
		ginflist.add(new GameInfo(8, "Newcastle Utd", "Brighton", 0, 1, "St James' Park", 52220));
		ginflist.add(new GameInfo(8, "Bournemouth", "Arsenal", 2, 0, "Vitality Stadium", 11235));
		ginflist.add(new GameInfo(8, "Wolves", "Manchester City", 1, 2, "Molineux Stadium", 31319));
		ginflist.add(new GameInfo(8, "Liverpool", "Chelsea", 2, 1, "Anfield", 60277));
		ginflist.add(new GameInfo(8, "Nott'ham Forest", "Crystal Palace", 1, 0, "The City Ground", 29443));
		ginflist.add(new GameInfo(9, "Leicester City", "Nott'ham Forest", 1, 3, "King Power Stadium", 31879));
		ginflist.add(new GameInfo(9, "Brighton", "Wolves", 2, 2, "The American Express Stadium", 31840));
		ginflist.add(new GameInfo(9, "Manchester City", "Southampton", 1, 0, "Etihad Stadium", 52844));
		ginflist.add(new GameInfo(9, "Brentford", "Ipswich Town", 4, 3, "Gtech Community Stadium", 17109));
		ginflist.add(new GameInfo(9, "Aston Villa", "Bournemouth", 1, 1, "Villa Park", 42165));
		ginflist.add(new GameInfo(9, "Everton", "Fulham", 1, 1, "Goodison Park", 38742));
		ginflist.add(new GameInfo(9, "West Ham", "Manchester Utd", 2, 1, "London Stadium", 62474));
		ginflist.add(new GameInfo(9, "Chelsea", "Newcastle Utd", 2, 1, "Stamford Bridge", 39526));
		ginflist.add(new GameInfo(9, "Crystal Palace", "Tottenham", 1, 0, "Selhurst Park", 25108));
		ginflist.add(new GameInfo(9, "Arsenal", "Liverpool", 2, 2, "Emirates Stadium", 60383));
		ginflist.add(new GameInfo(10, "Newcastle Utd", "Arsenal", 1, 0, "St James' Park", 52249));
		ginflist.add(new GameInfo(10, "Liverpool", "Brighton", 2, 1, "Anfield", 60331));
		ginflist.add(new GameInfo(10, "Southampton", "Everton", 1, 0, "St Mary's Stadium", 31143));
		ginflist.add(new GameInfo(10, "Nott'ham Forest", "West Ham", 3, 0, "The City Ground", 30112));
		ginflist.add(new GameInfo(10, "Ipswich Town", "Leicester City", 1, 1, "Portman Road Stadium", 29874));
		ginflist.add(new GameInfo(10, "Bournemouth", "Manchester City", 2, 1, "Vitality Stadium", 11231));
		ginflist.add(new GameInfo(10, "Wolves", "Crystal Palace", 2, 2, "Molineux Stadium", 31124));
		ginflist.add(new GameInfo(10, "Tottenham", "Aston Villa", 4, 1, "Tottenham Hotspur Stadium", 61253));
		ginflist.add(new GameInfo(10, "Manchester Utd", "Chelsea", 1, 1, "Old Trafford", 73813));
		ginflist.add(new GameInfo(10, "Fulham", "Brentford", 2, 1, "Craven Cottage", 24931));
		ginflist.add(new GameInfo(11, "West Ham", "Everton", 0, 0, "London Stadium", 62463));
		ginflist.add(new GameInfo(11, "Crystal Palace", "Fulham", 0, 2, "Selhurst Park", 25142));
		ginflist.add(new GameInfo(11, "Wolves", "Southampton", 2, 0, "Molineux Stadium", 31403));
		ginflist.add(new GameInfo(11, "Brentford", "Bournemouth", 3, 2, "Gtech Community Stadium", 16587));
		ginflist.add(new GameInfo(11, "Brighton", "Manchester City", 2, 1, "The American Express Stadium", 31715));
		ginflist.add(new GameInfo(11, "Liverpool", "Aston Villa", 2, 0, "Anfield", 60292));
		ginflist.add(new GameInfo(11, "Tottenham", "Ipswich Town", 1, 2, "Tottenham Hotspur Stadium", 61505));
		ginflist.add(new GameInfo(11, "Nott'ham Forest", "Newcastle Utd", 1, 3, "The City Ground", 30145));
		ginflist.add(new GameInfo(11, "Manchester Utd", "Leicester City", 3, 0, "Old Trafford", 73829));
		ginflist.add(new GameInfo(11, "Chelsea", "Arsenal", 1, 1, "Stamford Bridge", 39780));
		ginflist.add(new GameInfo(12, "Leicester City", "Chelsea", 1, 2, "King Power Stadium", 31880));
		ginflist.add(new GameInfo(12, "Aston Villa", "Crystal Palace", 2, 2, "Villa Park", 42175));
		ginflist.add(new GameInfo(12, "Fulham", "Wolves", 1, 4, "Craven Cottage", 26685));
		ginflist.add(new GameInfo(12, "Bournemouth", "Brighton", 1, 2, "Vitality Stadium", 11196));
		ginflist.add(new GameInfo(12, "Arsenal", "Nott'ham Forest", 3, 0, "Emirates Stadium", 60298));
		ginflist.add(new GameInfo(12, "Everton", "Brentford", 0, 0, "Goodison Park", 38915));
		ginflist.add(new GameInfo(12, "Manchester City", "Tottenham", 0, 4, "Etihad Stadium", 52478));
		ginflist.add(new GameInfo(12, "Southampton", "Liverpool", 2, 3, "St Mary's Stadium", 31278));
		ginflist.add(new GameInfo(12, "Ipswich Town", "Manchester Utd", 1, 1, "Portman Road Stadium", 30017));
		ginflist.add(new GameInfo(12, "Newcastle Utd", "West Ham", 0, 2, "St James' Park", 52094));
		ginflist.add(new GameInfo(13, "Brighton", "Southampton", 1, 1, "The American Express Stadium", 31542));
		ginflist.add(new GameInfo(13, "Wolves", "Bournemouth", 2, 4, "Molineux Stadium", 26685));
		ginflist.add(new GameInfo(13, "Nott'ham Forest", "Ipswich Town", 1, 0, "The City Ground", 30237));
		ginflist.add(new GameInfo(13, "Brentford", "Leicester City", 4, 1, "Gtech Community Stadium", 17084));
		ginflist.add(new GameInfo(13, "Crystal Palace", "Newcastle Utd", 1, 1, "Selhurst Park", 25101));
		ginflist.add(new GameInfo(13, "West Ham", "Arsenal", 2, 5, "London Stadium", 62475));
		ginflist.add(new GameInfo(13, "Manchester Utd", "Everton", 4, 0, "Old Trafford", 73817));
		ginflist.add(new GameInfo(13, "Tottenham", "Fulham", 1, 1, "Tottenham Hotspur Stadium", 61141));
		ginflist.add(new GameInfo(13, "Chelsea", "Aston Villa", 3, 0, "Stamford Bridge", 40853));
		ginflist.add(new GameInfo(13, "Liverpool", "Manchester City", 2, 0, "Anfield", 60248));
		ginflist.add(new GameInfo(14, "Ipswich Town", "Crystal Palace", 0, 1, "Portman Road Stadium", 29533));
		ginflist.add(new GameInfo(14, "Leicester City", "West Ham", 3, 1, "King Power Stadium", 30947));
		ginflist.add(new GameInfo(14, "Newcastle Utd", "Liverpool", 3, 3, "St James' Park", 52237));
		ginflist.add(new GameInfo(14, "Everton", "Wolves", 4, 0, "Goodison Park", 38820));
		ginflist.add(new GameInfo(14, "Manchester City", "Nott'ham Forest", 3, 0, "Etihad Stadium", 51764));
		ginflist.add(new GameInfo(14, "Southampton", "Chelsea", 1, 5, "St Mary's Stadium", 31193));
		ginflist.add(new GameInfo(14, "Arsenal", "Manchester Utd", 2, 0, "Emirates Stadium", 60256));
		ginflist.add(new GameInfo(14, "Aston Villa", "Brentford", 3, 1, "Villa Park", 42148));
		ginflist.add(new GameInfo(14, "Fulham", "Brighton", 3, 1, "Craven Cottage", 26368));
		ginflist.add(new GameInfo(14, "Bournemouth", "Tottenham", 1, 0, "Vitality Stadium", 11234));
		ginflist.add(new GameInfo(15, "Aston Villa", "Southampton", 1, 0, "Villa Park", 42453));
		ginflist.add(new GameInfo(15, "Crystal Palace", "Manchester City", 2, 2, "Selhurst Park", 25142));
		ginflist.add(new GameInfo(15, "Brentford", "Newcastle Utd", 4, 2, "Gtech Community Stadium", 17078));
		ginflist.add(new GameInfo(15, "Manchester Utd", "Nott'ham Forest", 2, 3, "Old Trafford", 73778));
		ginflist.add(new GameInfo(15, "Leicester City", "Brighton", 2, 2, "King Power Stadium", 31647));
		ginflist.add(new GameInfo(15, "Ipswich Town", "Bournemouth", 1, 2, "Portman Road Stadium", 29180));
		ginflist.add(new GameInfo(15, "Fulham", "Arsenal", 1, 1, "Craven Cottage", 26954));
		ginflist.add(new GameInfo(15, "Tottenham", "Chelsea", 3, 4, "Tottenham Hotspur Stadium", 61184));
		ginflist.add(new GameInfo(15, "West Ham", "Wolves", 2, 1, "London Stadium", 62474));
		ginflist.add(new GameInfo(16, "Liverpool", "Fulham", 2, 2, "Anfield", 60333));
		ginflist.add(new GameInfo(16, "Wolves", "Ipswich Town", 1, 2, "Molineux Stadium", 30866));
		ginflist.add(new GameInfo(16, "Newcastle Utd", "Leicester City", 4, 0, "St James' Park", 52235));
		ginflist.add(new GameInfo(16, "Arsenal", "Everton", 0, 0, "Emirates Stadium", 60176));
		ginflist.add(new GameInfo(16, "Nott'ham Forest", "Aston Villa", 2, 1, "The City Ground", 30117));
		ginflist.add(new GameInfo(16, "Brighton", "Crystal Palace", 1, 3, "The American Express Stadium", 30893));
		ginflist.add(new GameInfo(16, "Manchester City", "Manchester Utd", 1, 2, "Etihad Stadium", 53184));
		ginflist.add(new GameInfo(16, "Southampton", "Tottenham", 0, 5, "St Mary's Stadium", 31090));
		ginflist.add(new GameInfo(16, "Chelsea", "Brentford", 2, 1, "Stamford Bridge", 39571));
		ginflist.add(new GameInfo(16, "Bournemouth", "West Ham", 1, 1, "Vitality Stadium", 11204));
		ginflist.add(new GameInfo(17, "Aston Villa", "Manchester City", 2, 1, "Villa Park", 42345));
		ginflist.add(new GameInfo(17, "Ipswich Town", "Newcastle Utd", 0, 4, "Portman Road Stadium", 29774));
		ginflist.add(new GameInfo(17, "Brentford", "Nott'ham Forest", 0, 2, "Gtech Community Stadium", 17115));
		ginflist.add(new GameInfo(17, "West Ham", "Brighton", 1, 1, "London Stadium", 62460));
		ginflist.add(new GameInfo(17, "Crystal Palace", "Arsenal", 1, 5, "Selhurst Park", 25167));
		ginflist.add(new GameInfo(17, "Manchester Utd", "Bournemouth", 0, 3, "Old Trafford", 73720));
		ginflist.add(new GameInfo(17, "Leicester City", "Wolves", 0, 3, "King Power Stadium", 31818));
		ginflist.add(new GameInfo(17, "Everton", "Chelsea", 0, 0, "Goodison Park", 39358));
		ginflist.add(new GameInfo(17, "Fulham", "Southampton", 0, 0, "Craven Cottage", 26819));
		ginflist.add(new GameInfo(17, "Tottenham", "Liverpool", 3, 6, "Tottenham Hotspur Stadium", 61439));
		ginflist.add(new GameInfo(18, "Manchester City", "Everton", 1, 1, "Etihad Stadium", 55527));
		ginflist.add(new GameInfo(18, "Southampton", "West Ham", 0, 1, "St Mary's Stadium", 31059));
		ginflist.add(new GameInfo(18, "Newcastle Utd", "Aston Villa", 3, 0, "St James' Park", 52168));
		ginflist.add(new GameInfo(18, "Nott'ham Forest", "Tottenham", 1, 0, "The City Ground", 30200));
		ginflist.add(new GameInfo(18, "Bournemouth", "Crystal Palace", 0, 0, "Vitality Stadium", 11129));
		ginflist.add(new GameInfo(18, "Chelsea", "Fulham", 1, 2, "Stamford Bridge", 39687));
		ginflist.add(new GameInfo(18, "Wolves", "Manchester Utd", 2, 0, "Molineux Stadium", 31407));
		ginflist.add(new GameInfo(18, "Liverpool", "Leicester City", 3, 1, "Anfield", 60300));
		ginflist.add(new GameInfo(18, "Brighton", "Brentford", 0, 0, "The American Express Stadium", 31548));
		ginflist.add(new GameInfo(18, "Arsenal", "Ipswich Town", 1, 0, "Emirates Stadium", 60271));
		ginflist.add(new GameInfo(19, "Leicester City", "Manchester City", 0, 2, "King Power Stadium", 32057));
		ginflist.add(new GameInfo(19, "Everton", "Nott'ham Forest", 0, 2, "Goodison Park", 25414));
		ginflist.add(new GameInfo(19, "Tottenham", "Wolves", 2, 2, "Tottenham Hotspur Stadium", 61284));
		ginflist.add(new GameInfo(19, "Fulham", "Bournemouth", 2, 2, "Craven Cottage", 27301));
		ginflist.add(new GameInfo(19, "Crystal Palace", "Southampton", 2, 1, "Selhurst Park", 25130));
		ginflist.add(new GameInfo(19, "West Ham", "Liverpool", 0, 5, "London Stadium", 62476));
		ginflist.add(new GameInfo(19, "Aston Villa", "Brighton", 2, 2, "Villa Park", 41414));
		ginflist.add(new GameInfo(19, "Ipswich Town", "Chelsea", 2, 0, "Portman Road Stadium", 29968));
		ginflist.add(new GameInfo(19, "Manchester Utd", "Newcastle Utd", 0, 2, "Old Trafford", 73809));
		ginflist.add(new GameInfo(19, "Brentford", "Arsenal", 1, 3, "Gtech Community Stadium", 47190));
		ginflist.add(new GameInfo(20, "Tottenham", "Newcastle Utd", 1, 2, "Tottenham Hotspur Stadium", 61293));
		ginflist.add(new GameInfo(20, "Aston Villa", "Leicester City", 2, 1, "Villa Park", 42386));
		ginflist.add(new GameInfo(20, "Bournemouth", "Everton", 1, 0, "Vitality Stadium", 11223));
		ginflist.add(new GameInfo(20, "Crystal Palace", "Chelsea", 1, 1, "Selhurst Park", 25179));
		ginflist.add(new GameInfo(20, "Southampton", "Brentford", 0, 5, "St Mary's Stadium", 31001));
		ginflist.add(new GameInfo(20, "Manchester City", "West Ham", 4, 1, "Etihad Stadium", 52737));
		ginflist.add(new GameInfo(20, "Brighton", "Arsenal", 1, 1, "The American Express Stadium", 31714));
		ginflist.add(new GameInfo(20, "Fulham", "Ipswich Town", 2, 2, "Craven Cottage", 27042));
		ginflist.add(new GameInfo(20, "Liverpool", "Manchester Utd", 2, 2, "Anfield", 60275));
		ginflist.add(new GameInfo(20, "Wolves", "Nott'ham Forest", 0, 3, "Molineux Stadium", 29940));
		ginflist.add(new GameInfo(21, "West Ham", "Fulham", 3, 2, "London Stadium", 62456));
		ginflist.add(new GameInfo(21, "Chelsea", "Bournemouth", 2, 2, "Stamford Bridge", 39092));
		ginflist.add(new GameInfo(21, "Brentford", "Manchester City", 2, 2, "Gtech Community Stadium", 17048));
		ginflist.add(new GameInfo(21, "Nott'ham Forest", "Liverpool", 1, 1, "The City Ground", 30249));
		ginflist.add(new GameInfo(21, "Leicester City", "Crystal Palace", 0, 2, "King Power Stadium", 29766));
		ginflist.add(new GameInfo(21, "Everton", "Aston Villa", 0, 1, "Goodison Park", 39085));
		ginflist.add(new GameInfo(21, "Newcastle Utd", "Wolves", 3, 0, "St James' Park", 51975));
		ginflist.add(new GameInfo(21, "Arsenal", "Tottenham", 2, 1, "Emirates Stadium", 60287));
		ginflist.add(new GameInfo(21, "Ipswich Town", "Brighton", 0, 2, "Portman Road Stadium", 29403));
		ginflist.add(new GameInfo(21, "Manchester Utd", "Southampton", 3, 1, "Old Trafford", 73722));
		ginflist.add(new GameInfo(22, "Newcastle Utd", "Bournemouth", 1, 4, "St James' Park", 52227));
		ginflist.add(new GameInfo(22, "Leicester City", "Fulham", 0, 2, "King Power Stadium", 31500));
		ginflist.add(new GameInfo(22, "West Ham", "Crystal Palace", 0, 2, "London Stadium", 62469));
		ginflist.add(new GameInfo(22, "Brentford", "Liverpool", 0, 2, "Gtech Community Stadium", 17215));
		ginflist.add(new GameInfo(22, "Arsenal", "Aston Villa", 2, 2, "Emirates Stadium", 60067));
		ginflist.add(new GameInfo(22, "Everton", "Tottenham", 3, 2, "Goodison Park", 39326));
		ginflist.add(new GameInfo(22, "Manchester Utd", "Brighton", 1, 3, "Old Trafford", 73758));
		ginflist.add(new GameInfo(22, "Nott'ham Forest", "Southampton", 3, 2, "The City Ground", 30180));
		ginflist.add(new GameInfo(22, "Ipswich Town", "Manchester City", 0, 6, "Portman Road Stadium", 29841));
		ginflist.add(new GameInfo(22, "Chelsea", "Wolves", 3, 1, "Stamford Bridge", 39221));
		ginflist.add(new GameInfo(23, "Southampton", "Newcastle Utd", 1, 3, "St Mary's Stadium", 31141));
		ginflist.add(new GameInfo(23, "Brighton", "Everton", 0, 1, "The American Express Stadium", 31087));
		ginflist.add(new GameInfo(23, "Liverpool", "Ipswich Town", 4, 1, "Anfield", 60420));
		ginflist.add(new GameInfo(23, "Bournemouth", "Nott'ham Forest", 5, 0, "Vitality Stadium", 11228));
		ginflist.add(new GameInfo(23, "Wolves", "Arsenal", 0, 1, "Molineux Stadium", 31503));
		ginflist.add(new GameInfo(23, "Manchester City", "Chelsea", 3, 1, "Etihad Stadium", 52687));
		ginflist.add(new GameInfo(23, "Crystal Palace", "Brentford", 1, 2, "Selhurst Park", 25066));
		ginflist.add(new GameInfo(23, "Tottenham", "Leicester City", 1, 2, "Tottenham Hotspur Stadium", 61295));
		ginflist.add(new GameInfo(23, "Aston Villa", "West Ham", 1, 1, "Villa Park", 41628));
		ginflist.add(new GameInfo(23, "Fulham", "Manchester Utd", 0, 1, "Craven Cottage", 27288));
		ginflist.add(new GameInfo(24, "Nott'ham Forest", "Brighton", 7, 0, "The City Ground", 30164));
		ginflist.add(new GameInfo(24, "Everton", "Leicester City", 4, 0, "Goodison Park", 39376));
		ginflist.add(new GameInfo(24, "Newcastle Utd", "Fulham", 1, 2, "St James' Park", 52173));
		ginflist.add(new GameInfo(24, "Bournemouth", "Liverpool", 0, 2, "Vitality Stadium", 11239));
		ginflist.add(new GameInfo(24, "Ipswich Town", "Southampton", 1, 2, "Portman Road Stadium", 29902));
		ginflist.add(new GameInfo(24, "Wolves", "Aston Villa", 2, 0, "Molineux Stadium", 31385));
		ginflist.add(new GameInfo(24, "Manchester Utd", "Crystal Palace", 0, 2, "Old Trafford", 73751));
		ginflist.add(new GameInfo(24, "Brentford", "Tottenham", 0, 2, "Gtech Community Stadium", 17154));
		ginflist.add(new GameInfo(24, "Arsenal", "Manchester City", 5, 1, "Emirates Stadium", 60355));
		ginflist.add(new GameInfo(24, "Chelsea", "West Ham", 2, 1, "Stamford Bridge", 39459));
		ginflist.add(new GameInfo(15, "Everton", "Liverpool", 2, 2, "Goodison Park", 39280));
		ginflist.add(new GameInfo(25, "Brighton", "Chelsea", 3, 0, "The American Express Stadium", 31324));
		ginflist.add(new GameInfo(25, "Leicester City", "Arsenal", 0, 2, "King Power Stadium", 31968));
		ginflist.add(new GameInfo(25, "Fulham", "Nott'ham Forest", 2, 1, "Craven Cottage", 27164));
		ginflist.add(new GameInfo(25, "Manchester City", "Newcastle Utd", 4, 0, "Etihad Stadium", 52479));
		ginflist.add(new GameInfo(25, "Southampton", "Bournemouth", 1, 3, "St Mary's Stadium", 31037));
		ginflist.add(new GameInfo(25, "Aston Villa", "Ipswich Town", 1, 1, "Villa Park", 42510));
		ginflist.add(new GameInfo(25, "West Ham", "Brentford", 0, 1, "London Stadium", 62415));
		ginflist.add(new GameInfo(25, "Crystal Palace", "Everton", 1, 2, "Selhurst Park", 25108));
		ginflist.add(new GameInfo(25, "Liverpool", "Wolves", 2, 1, "Anfield", 60248));
		ginflist.add(new GameInfo(25, "Tottenham", "Manchester Utd", 1, 0, "Tottenham Hotspur Stadium", 61383));
		ginflist.add(new GameInfo(29, "Aston Villa", "Liverpool", 2, 2, "Villa Park", 41910));
		ginflist.add(new GameInfo(26, "Leicester City", "Brentford", 0, 4, "King Power Stadium", 31077));
		ginflist.add(new GameInfo(26, "Everton", "Manchester Utd", 2, 2, "Goodison Park", 39290));
		ginflist.add(new GameInfo(26, "Fulham", "Crystal Palace", 0, 2, "Craven Cottage", 26777));
		ginflist.add(new GameInfo(26, "Bournemouth", "Wolves", 0, 1, "Vitality Stadium", 11206));
		ginflist.add(new GameInfo(26, "Ipswich Town", "Tottenham", 1, 4, "Portman Road Stadium", 30003));
		ginflist.add(new GameInfo(26, "Arsenal", "West Ham", 0, 1, "Emirates Stadium", 60262));
		ginflist.add(new GameInfo(26, "Southampton", "Brighton", 0, 4, "St Mary's Stadium", 30775));
		ginflist.add(new GameInfo(26, "Aston Villa", "Chelsea", 2, 1, "Villa Park", 42423));
		ginflist.add(new GameInfo(26, "Newcastle Utd", "Nott'ham Forest", 4, 3, "St James' Park", 52223));
		ginflist.add(new GameInfo(26, "Manchester City", "Liverpool", 0, 2, "Etihad Stadium", 52803));
		ginflist.add(new GameInfo(27, "Brighton", "Bournemouth", 2, 1, "The American Express Stadium", 31138));
		ginflist.add(new GameInfo(27, "Crystal Palace", "Aston Villa", 4, 1, "Selhurst Park", 24712));
		ginflist.add(new GameInfo(27, "Wolves", "Fulham", 1, 2, "Molineux Stadium", 28708));
		ginflist.add(new GameInfo(27, "Chelsea", "Southampton", 4, 0, "Stamford Bridge", 39485));
		ginflist.add(new GameInfo(27, "Tottenham", "Manchester City", 0, 1, "Tottenham Hotspur Stadium", 60820));
		ginflist.add(new GameInfo(27, "Nott'ham Forest", "Arsenal", 0, 0, "The City Ground", 30200));
		ginflist.add(new GameInfo(27, "Manchester Utd", "Ipswich Town", 3, 2, "Old Trafford", 73827));
		ginflist.add(new GameInfo(27, "Brentford", "Everton", 1, 1, "Gtech Community Stadium", 17082));
		ginflist.add(new GameInfo(27, "Liverpool", "Newcastle Utd", 2, 0, "Anfield", 60374));
		ginflist.add(new GameInfo(27, "West Ham", "Leicester City", 2, 0, "London Stadium", 62455));
		ginflist.add(new GameInfo(28, "Nott'ham Forest", "Manchester City", 1, 0, "The City Ground", 30252));
		ginflist.add(new GameInfo(28, "Liverpool", "Southampton", 3, 1, "Anfield", 60399));
		ginflist.add(new GameInfo(28, "Brighton", "Fulham", 2, 1, "The American Express Stadium", 31584));
		ginflist.add(new GameInfo(28, "Crystal Palace", "Ipswich Town", 1, 0, "Selhurst Park", 25155));
		ginflist.add(new GameInfo(28, "Brentford", "Aston Villa", 0, 1, "Gtech Community Stadium", 17171));
		ginflist.add(new GameInfo(28, "Wolves", "Everton", 1, 1, "Molineux Stadium", 30738));
		ginflist.add(new GameInfo(28, "Chelsea", "Leicester City", 1, 0, "Stamford Bridge", 39750));
		ginflist.add(new GameInfo(28, "Tottenham", "Bournemouth", 2, 2, "Tottenham Hotspur Stadium", 61178));
		ginflist.add(new GameInfo(28, "Manchester Utd", "Arsenal", 1, 1, "Old Trafford", 73812));
		ginflist.add(new GameInfo(28, "West Ham", "Newcastle Utd", 0, 1, "London Stadium", 62463));
		ginflist.add(new GameInfo(29, "Everton", "West Ham", 1, 1, "Goodison Park", 39343));
		ginflist.add(new GameInfo(29, "Southampton", "Wolves", 1, 2, "St Mary's Stadium", 30950));
		ginflist.add(new GameInfo(29, "Ipswich Town", "Nott'ham Forest", 2, 4, "Portman Road Stadium", 29878));
		ginflist.add(new GameInfo(29, "Manchester City", "Brighton", 2, 2, "Etihad Stadium", 52471));
		ginflist.add(new GameInfo(29, "Bournemouth", "Brentford", 1, 2, "Vitality Stadium", 11180));
		ginflist.add(new GameInfo(29, "Arsenal", "Chelsea", 1, 0, "Emirates Stadium", 60311));
		ginflist.add(new GameInfo(29, "Fulham", "Tottenham", 2, 0, "Craven Cottage", 27182));
		ginflist.add(new GameInfo(29, "Leicester City", "Manchester Utd", 0, 3, "King Power Stadium", 31773));
		ginflist.add(new GameInfo(30, "Arsenal", "Fulham", 2, 1, "Emirates Stadium", 60256));
		ginflist.add(new GameInfo(30, "Wolves", "West Ham", 1, 0, "Molineux Stadium", 29587));
		ginflist.add(new GameInfo(30, "Nott'ham Forest", "Manchester Utd", 1, 0, "The City Ground", 30249));
		ginflist.add(new GameInfo(30, "Newcastle Utd", "Brentford", 2, 1, "St James' Park", 52021));
		ginflist.add(new GameInfo(30, "Manchester City", "Leicester City", 2, 0, "Etihad Stadium", 52148));
		ginflist.add(new GameInfo(30, "Southampton", "Crystal Palace", 1, 1, "St Mary's Stadium", 30158));
		ginflist.add(new GameInfo(30, "Bournemouth", "Ipswich Town", 1, 2, "Vitality Stadium", 11192));
		ginflist.add(new GameInfo(30, "Brighton", "Aston Villa", 0, 3, "The American Express Stadium", 27895));
		ginflist.add(new GameInfo(30, "Liverpool", "Everton", 1, 0, "Anfield", 60457));
		ginflist.add(new GameInfo(30, "Chelsea", "Tottenham", 1, 0, "Stamford Bridge", 39852));
		ginflist.add(new GameInfo(31, "Everton", "Arsenal", 1, 1, "Goodison Park", 39316));
		ginflist.add(new GameInfo(31, "Crystal Palace", "Brighton", 2, 1, "Selhurst Park", 24564));
		ginflist.add(new GameInfo(31, "Ipswich Town", "Wolves", 1, 2, "Portman Road Stadium", 29549));
		ginflist.add(new GameInfo(31, "West Ham", "Bournemouth", 2, 2, "London Stadium", 62459));
		ginflist.add(new GameInfo(31, "Aston Villa", "Nott'ham Forest", 2, 1, "Villa Park", 42743));
		ginflist.add(new GameInfo(31, "Fulham", "Liverpool", 3, 2, "Craven Cottage", 27770));
		ginflist.add(new GameInfo(31, "Brentford", "Chelsea", 0, 0, "Gtech Community Stadium", 17183));
		ginflist.add(new GameInfo(31, "Tottenham", "Southampton", 3, 1, "Tottenham Hotspur Stadium", 60984));
		ginflist.add(new GameInfo(31, "Manchester Utd", "Manchester City", 0, 0, "Old Trafford", 73738));
		ginflist.add(new GameInfo(31, "Leicester City", "Newcastle Utd", 0, 3, "King Power Stadium", 30403));
		ginflist.add(new GameInfo(32, "Manchester City", "Crystal Palace", 5, 2, "Etihad Stadium", 52489));
		ginflist.add(new GameInfo(32, "Brighton", "Leicester City", 2, 2, "The American Express Stadium", 31150));
		ginflist.add(new GameInfo(32, "Southampton", "Aston Villa", 0, 3, "St Mary's Stadium", 30199));
		ginflist.add(new GameInfo(32, "Nott'ham Forest", "Everton", 0, 1, "The City Ground", 30199));
		ginflist.add(new GameInfo(32, "Arsenal", "Brentford", 1, 1, "Emirates Stadium", 60184));
		ginflist.add(new GameInfo(32, "Liverpool", "West Ham", 2, 1, "Anfield", 60376));
		ginflist.add(new GameInfo(32, "Chelsea", "Ipswich Town", 2, 2, "Stamford Bridge", 39805));
		ginflist.add(new GameInfo(32, "Wolves", "Tottenham", 4, 2, "Molineux Stadium", 31463));
		ginflist.add(new GameInfo(32, "Newcastle Utd", "Manchester Utd", 4, 1, "St James' Park", 52252));
		ginflist.add(new GameInfo(32, "Bournemouth", "Fulham", 1, 0, "Vitality Stadium", 11195));
		ginflist.add(new GameInfo(29, "Newcastle Utd", "Crystal Palace", 5, 0, "St James' Park", 52197));
		ginflist.add(new GameInfo(33, "Everton", "Manchester City", 0, 2, "Goodison Park", 39332));
		ginflist.add(new GameInfo(33, "West Ham", "Southampton", 1, 1, "London Stadium", 62461));
		ginflist.add(new GameInfo(33, "Crystal Palace", "Bournemouth", 0, 0, "Selhurst Park", 25185));
		ginflist.add(new GameInfo(33, "Brentford", "Brighton", 4, 2, "Gtech Community Stadium", 17083));
		ginflist.add(new GameInfo(33, "Aston Villa", "Newcastle Utd", 4, 1, "Villa Park", 42618));
		ginflist.add(new GameInfo(33, "Fulham", "Chelsea", 1, 2, "Craven Cottage", 27712));
		ginflist.add(new GameInfo(33, "Ipswich Town", "Arsenal", 0, 4, "Portman Road Stadium", 29549));
		ginflist.add(new GameInfo(33, "Manchester Utd", "Wolves", 0, 1, "Old Trafford", 73819));
		ginflist.add(new GameInfo(33, "Leicester City", "Liverpool", 0, 1, "King Power Stadium", 30402));
		ginflist.add(new GameInfo(33, "Tottenham", "Nott'ham Forest", 1, 2, "Tottenham Hotspur Stadium", 59314));
		ginflist.add(new GameInfo(34, "Manchester City", "Aston Villa", 2, 1, "Etihad Stadium", 51834));
		ginflist.add(new GameInfo(34, "Arsenal", "Crystal Palace", 2, 2, "Emirates Stadium", 60167));
		ginflist.add(new GameInfo(34, "Chelsea", "Everton", 1, 0, "Stamford Bridge", 39894));
		ginflist.add(new GameInfo(34, "Brighton", "West Ham", 3, 2, "The American Express Stadium", 31499));
		ginflist.add(new GameInfo(34, "Wolves", "Leicester City", 3, 0, "Molineux Stadium", 31518));
		ginflist.add(new GameInfo(34, "Southampton", "Fulham", 1, 2, "St Mary's Stadium", 28946));
		ginflist.add(new GameInfo(34, "Newcastle Utd", "Ipswich Town", 3, 0, "St James' Park", 52171));
		ginflist.add(new GameInfo(34, "Bournemouth", "Manchester Utd", 1, 1, "Vitality Stadium", 11241));
		ginflist.add(new GameInfo(34, "Liverpool", "Tottenham", 5, 1, "Anfield", 60415));
		ginflist.add(new GameInfo(34, "Nott'ham Forest", "Brentford", 0, 2, "The City Ground", 29040));
		ginflist.add(new GameInfo(35, "Manchester City", "Wolves", 1, 0, "Etihad Stadium", 53282));
		ginflist.add(new GameInfo(35, "Aston Villa", "Fulham", 1, 0, "Villa Park", 42515));
		ginflist.add(new GameInfo(35, "Leicester City", "Southampton", 2, 0, "King Power Stadium", 31240));
		ginflist.add(new GameInfo(35, "Everton", "Ipswich Town", 2, 2, "Goodison Park", 39305));
		ginflist.add(new GameInfo(35, "Arsenal", "Bournemouth", 1, 2, "Emirates Stadium", 60110));
		ginflist.add(new GameInfo(35, "Brighton", "Newcastle Utd", 1, 1, "The American Express Stadium", 31580));
		ginflist.add(new GameInfo(35, "West Ham", "Tottenham", 1, 1, "London Stadium", 62468));
		ginflist.add(new GameInfo(35, "Brentford", "Manchester Utd", 4, 3, "Gtech Community Stadium", 18915));
		ginflist.add(new GameInfo(35, "Chelsea", "Liverpool", 3, 1, "Stamford Bridge", 39829));
		ginflist.add(new GameInfo(35, "Crystal Palace", "Nott'ham Forest", 1, 1, "Selhurst Park", 25096));
		ginflist.add(new GameInfo(36, "Ipswich Town", "Brentford", 0, 1, "Portman Road Stadium", 29511));
		ginflist.add(new GameInfo(36, "Fulham", "Everton", 1, 3, "Craven Cottage", 27653));
		ginflist.add(new GameInfo(36, "Wolves", "Brighton", 0, 2, "Molineux Stadium", 31279));
		ginflist.add(new GameInfo(36, "Southampton", "Manchester City", 0, 0, "St Mary's Stadium", 30937));
		ginflist.add(new GameInfo(36, "Bournemouth", "Aston Villa", 0, 1, "Vitality Stadium", 11187));
		ginflist.add(new GameInfo(36, "Newcastle Utd", "Chelsea", 2, 0, "St James' Park", 52231));
		ginflist.add(new GameInfo(36, "Nott'ham Forest", "Leicester City", 2, 2, "The City Ground", 30245));
		ginflist.add(new GameInfo(36, "Tottenham", "Crystal Palace", 0, 2, "Tottenham Hotspur Stadium", 60254));
		ginflist.add(new GameInfo(36, "Manchester Utd", "West Ham", 0, 2, "Old Trafford", 73804));
		ginflist.add(new GameInfo(36, "Liverpool", "Arsenal", 2, 2, "Anfield", 60324));
		ginflist.add(new GameInfo(37, "Aston Villa", "Tottenham", 2, 0, "Villa Park", 42239));
		ginflist.add(new GameInfo(37, "Chelsea", "Manchester Utd", 1, 0, "Stamford Bridge", 39849));
		ginflist.add(new GameInfo(37, "Everton", "Southampton", 2, 0, "Goodison Park", 39201));
		ginflist.add(new GameInfo(37, "West Ham", "Nott'ham Forest", 1, 2, "London Stadium", 62466));
		ginflist.add(new GameInfo(37, "Brentford", "Fulham", 2, 3, "Gtech Community Stadium", 17136));
		ginflist.add(new GameInfo(37, "Leicester City", "Ipswich Town", 2, 0, "King Power Stadium", 31986));
		ginflist.add(new GameInfo(37, "Arsenal", "Newcastle Utd", 1, 0, "Emirates Stadium", 60160));
		ginflist.add(new GameInfo(37, "Brighton", "Liverpool", 3, 2, "The American Express Stadium", 31611));
		ginflist.add(new GameInfo(37, "Manchester City", "Bournemouth", 3, 1, "Etihad Stadium", 52487));
		ginflist.add(new GameInfo(37, "Crystal Palace", "Wolves", 4, 2, "Selhurst Park", 24766));
		ginflist.add(new GameInfo(38, "Manchester Utd", "Aston Villa", 2, 0, "Old Trafford", 73839));
		ginflist.add(new GameInfo(38, "Ipswich Town", "West Ham", 1, 3, "Portman Road Stadium", 29771));
		ginflist.add(new GameInfo(38, "Wolves", "Brentford", 1, 1, "Molineux Stadium", 31382));
		ginflist.add(new GameInfo(38, "Southampton", "Arsenal", 1, 2, "St Mary's Stadium", 31289));
		ginflist.add(new GameInfo(38, "Liverpool", "Crystal Palace", 1, 1, "Anfield", 60382));
		ginflist.add(new GameInfo(38, "Nott'ham Forest", "Chelsea", 0, 1, "The City Ground", 30263));
		ginflist.add(new GameInfo(38, "Fulham", "Manchester City", 0, 2, "Craven Cottage", 27671));
		ginflist.add(new GameInfo(38, "Newcastle Utd", "Everton", 0, 1, "St James' Park", 52221));
		ginflist.add(new GameInfo(38, "Bournemouth", "Leicester City", 2, 0, "Vitality Stadium", 11238));
		ginflist.add(new GameInfo(38, "Tottenham", "Brighton", 1, 4, "Tottenham Hotspur Stadium", 61449));

	
		return ginflist;
	}

}
